# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7025e8c5d66ee3bb477520ced2f1e41c9c856a99cb477e6583c182610614c96fe6a5bbf5836e2d532965ae2c3533d7e38e17301193153e29b887d47e5d059b77

test:
  secret_key_base: c200c1e0140c37b06f625d858e1389729da4fd85189aed2e03397d885699309fe57c4e7c111a7557c0a57a30c03e7c65c6ed64b8e931ae6b3573c4c66aa3d17c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
